from __future__ import annotations

from typing import Dict, List, Set


PRODUCT_FIELDNAMES = [
    "id",
    "name",
    "project",
    "product_line",
    "sub_product",
    "product_system",
    "season_window_ids",
    "applicable_stages",
    "standard_capacity",
    "capacity_type",
    "subject_category",
    "subject",
    "course_nature",
    "notes",
]
PRODUCT_COURSE_FIELDNAMES = [
    "product_id",
    "product_name",
    "subject_category",
    "subject",
    "window_name",
    "stage",
    "stage_priority",
    "course_group",
    "course_module",
    "module_priority_in_group",
    "course_code",
    "course_name",
    "total_hours",
    "notes",
]
PRODUCT_RULE_FIELDNAMES = [
    "rule_id",
    "product_id",
    "product_name",
    "sub_product",
    "season_window_id",
    "window_name",
    "effective_after_class_start",
    "allowed_weekdays",
    "allowed_periods",
    "block_hours",
    "lessons_per_block",
    "max_hours_per_class_per_day",
    "max_blocks_per_class_per_day",
    "min_weekly_hours",
    "max_weekly_hours",
    "same_half_day_block_required",
    "same_half_day_4h_same_teacher_required",
    "delivery_mode",
    "notes",
]
TEACHING_AREA_FIELDNAMES = [
    "id",
    "name",
    "short_name",
    "region_tag",
    "address",
    "longitude",
    "latitude",
    "campus",
    "scheduling_capacity",
    "capacity_check",
    "is_active",
    "room_count",
    "active_room_count",
    "data_source",
    "notes",
]
ROOM_FIELDNAMES = [
    "id",
    "name",
    "teaching_area_id",
    "teaching_area_name",
    "campus",
    "capacity",
    "room_type",
    "is_active",
    "data_source",
    "notes",
]
TEACHER_FIELDNAMES = [
    "employee_id",
    "name",
    "gender",
    "project",
    "teacher_role",
    "employment_type",
    "primary_subject",
    "subject_type",
    "contract_status",
    "employment_status",
    "notes",
]
TEACHING_AREA_LINK_FIELDNAMES = [
    "id",
    "from_teaching_area_id",
    "to_teaching_area_id",
    "relation_type",
    "driving_distance_km",
    "travel_minutes",
    "notes",
]
CLASS_FIELDNAMES = [
    "id",
    "name",
    "product_id",
    "selected_stages",
    "project",
    "product_line",
    "sub_product",
    "product_system",
    "course_nature",
    "subject_category",
    "subject",
    "exam_season",
    "exam_month",
    "suite_code",
    "standard_capacity",
    "capacity_type",
    "size",
    "start_date",
    "start_period",
    "first_lesson_date",
    "first_lesson_period",
    "end_date",
    "end_period",
    "preferred_teaching_area_ids",
    "preferred_room_ids",
    "preferred_room_is_required",
    "is_manual_schedule_locked",
    "notes",
]
CLASS_CONFLICT_GROUP_FIELDNAMES = [
    "id",
    "name",
    "exam_season",
    "suite_code",
    "class_ids",
    "is_conflict_group_active",
    "conflict_source",
    "notes",
]
LOCKED_SCHEDULED_LESSON_FIELDNAMES = [
    "id",
    "class_id",
    "class_name",
    "date",
    "period",
    "start_time",
    "end_time",
    "duration_hours",
    "teacher_id",
    "teacher_name",
    "room_id",
    "room_name",
    "teaching_area_id",
    "business_product_id",
    "business_product_name",
    "subject",
    "window_name",
    "stage",
    "course_module",
    "course_group",
    "course_code",
    "course_name",
    "source",
    "is_locked",
    "notes",
]
HISTORICAL_SCHEDULED_LESSON_FIELDNAMES = [
    field for field in LOCKED_SCHEDULED_LESSON_FIELDNAMES if field != "is_locked"
]
TEACHER_ASSIGNMENT_FIELDNAMES = [
    "class_id",
    "class_name",
    "product_id",
    "product_name",
    "subject",
    "stage",
    "course_group",
    "class_schedule_mode",
    "actual_scheduled_class_id",
    "teacher_id",
    "teacher_name",
    "assignment_extra_time_requirement",
    "notes",
]
SCHEDULE_WINDOW_FIELDNAMES = [
    "schedule_window_id",
    "schedule_window_name",
    "window_year",
    "window_order",
    "season_window_id",
    "season_name",
    "start_date",
    "end_date",
    "default_allowed_periods",
    "default_allowed_weekdays",
    "is_active",
    "notes",
]
TIME_SLOT_FIELDNAMES = [
    "id",
    "date",
    "calendar_year",
    "schedule_window_id",
    "window_order",
    "weekday",
    "season_window_id",
    "season_name",
    "period",
    "half_day_id",
    "name",
    "order",
    "start_time",
    "end_time",
    "duration_hours",
    "is_usable",
    "availability_source",
    "unavailable_reason",
    "data_source",
]
TEACHER_UNAVAILABILITY_FIELDNAMES = [
    "unavailable_id",
    "employee_id",
    "teacher_name",
    "primary_subject",
    "unavailable_type",
    "start_date",
    "end_date",
    "weekdays",
    "periods",
    "schedule_window_ids",
    "is_active",
    "reason",
    "data_source",
    "notes",
]
GLOBAL_BLACKOUT_FIELDNAMES = ["id", "name", "start_date", "end_date", "is_active", "notes"]
CLASS_WINDOW_BOUNDARY_FIELDNAMES = [
    "class_window_id",
    "class_id",
    "class_name",
    "product_id",
    "schedule_window_id",
    "window_year",
    "window_order",
    "season_window_id",
    "season_name",
    "window_sequence",
    "schedule_window_name",
    "earliest_date",
    "earliest_period",
    "latest_date",
    "latest_period",
    "preferred_teaching_area_ids",
    "preferred_room_ids",
    "preferred_room_is_required",
    "is_class_window_included",
    "notes",
]
BUSINESS_PRODUCT_MAPPING_FIELDNAMES = [
    "local_product_id",
    "local_product_name",
    "local_product_line",
    "local_sub_product",
    "local_product_system",
    "local_course_nature",
    "local_subject",
    "erp_product_key",
    "erp_course_code",
    "erp_course_name",
    "erp_version_code",
    "erp_version_name",
    "erp_product_system",
    "erp_product_category",
    "erp_project_name",
    "erp_subject",
    "erp_class_type",
    "erp_duration_minutes",
    "erp_lesson_count",
    "erp_single_lesson_minutes",
    "erp_class_form",
    "erp_teaching_method",
    "match_status",
    "match_confidence",
    "match_source",
    "business_product_id",
    "business_product_name",
    "class_name_keywords",
    "notes",
]
ERP_STANDARD_PRODUCT_FIELDNAMES = [
    "erp_product_key",
    "course_code",
    "course_product_name_inner",
    "course_product_name_outer",
    "service_school_name",
    "management_project",
    "department",
    "product_system",
    "product_category",
    "course_category",
    "course_attribute",
    "project_name",
    "school",
    "subject",
    "product_brand",
    "learning_stage",
    "target_people",
    "group_class_type",
    "school_version_code",
    "school_version_name",
    "school_class_type",
    "standard_student_count",
    "opening_student_count",
    "guaranteed_student_count",
    "attendance_method",
    "class_price",
    "material_fee",
    "duration_minutes",
    "lesson_count",
    "hourly_price",
    "single_lesson_minutes",
    "class_form",
    "teaching_method",
    "teaching_channel",
    "is_enabled",
    "is_deleted",
    "is_teaching_method_valid",
    "operator",
    "operated_at",
    "reviewer",
    "reviewed_at",
    "source_file",
    "notes",
]

STANDARD_TABLE_FIELDNAMES: Dict[str, List[str]] = {
    "schedule_windows": SCHEDULE_WINDOW_FIELDNAMES,
    "time_slots": TIME_SLOT_FIELDNAMES,
    "teaching_areas": TEACHING_AREA_FIELDNAMES,
    "rooms": ROOM_FIELDNAMES,
    "teachers": TEACHER_FIELDNAMES,
    "teacher_unavailability": TEACHER_UNAVAILABILITY_FIELDNAMES,
    "products": PRODUCT_FIELDNAMES,
    "product_courses": PRODUCT_COURSE_FIELDNAMES,
    "product_schedule_rules": PRODUCT_RULE_FIELDNAMES,
    "classes": CLASS_FIELDNAMES,
    "class_window_boundaries": CLASS_WINDOW_BOUNDARY_FIELDNAMES,
    "class_teacher_assignments": TEACHER_ASSIGNMENT_FIELDNAMES,
    "class_conflict_groups": CLASS_CONFLICT_GROUP_FIELDNAMES,
    "locked_scheduled_lessons": LOCKED_SCHEDULED_LESSON_FIELDNAMES,
    "teaching_area_links": TEACHING_AREA_LINK_FIELDNAMES,
    "global_blackout_dates": GLOBAL_BLACKOUT_FIELDNAMES,
    "historical_scheduled_lessons": HISTORICAL_SCHEDULED_LESSON_FIELDNAMES,
    "business_product_mappings": BUSINESS_PRODUCT_MAPPING_FIELDNAMES,
    "erp_standard_products": ERP_STANDARD_PRODUCT_FIELDNAMES,
}
TABLES_WITH_EMPTY_WARNINGS: Set[str] = {"products", "product_courses", "product_schedule_rules"}
CLASS_JSON_EXTRA_FIELDNAMES = ["requirements", "teacher_assignments"]
